-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civirule_civiruleslogger_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civirule_civiruleslogger_log
-- *
-- * Civirules logger log
-- *
-- *******************************************************/
CREATE TABLE `civirule_civiruleslogger_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CivirulesLog ID',
  `message` varchar(128) NOT NULL COMMENT 'Standardized message',
  `context` longtext COMMENT 'JSON encoded data',
  `level` varchar(9) DEFAULT 'info' COMMENT 'error level per PSR3',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of when event occurred.',
  `contact_id` int unsigned DEFAULT NULL COMMENT 'Optional Contact ID that created the log. Not an FK as we keep this regardless',
  `rule_id` int unsigned DEFAULT NULL COMMENT 'Optional Rule ID that created the log',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
